pull_request_rules:
- actions:
    merge:
      strict: smart
      method: squash
      commit_message: title+body
  name: Automatically merge pull requests
  conditions:
  - or:
    - and:
      - -files~=\.hs$
      - -files~=\.sw$
      - -files~=\.cabal$
      - -files=stack.yaml
      - -files~=cabal.project.*
      - -files~=^[^/]*\.yaml$
      - -files~=^data/.*\.yaml$
    - and:
      - check-success=Haskell-CI - Linux - ghc-9.0.1
      - check-success=Haskell-CI - Linux - ghc-8.10.4
  - label=merge me
  - ! '#approved-reviews-by>=1'
  - ! '#changes-requested-reviews-by=0'
- actions:
    delete_head_branch: {}
  name: Delete head branch after merge
  conditions:
  - merged
