restylers_version: dev
restylers:
  - fourmolu:
      arguments:
        [ '--ghc-opt', '-XBangPatterns'
        , '--ghc-opt', '-XDeriveAnyClass'
        , '--ghc-opt', '-XDeriveDataTypeable'
        , '--ghc-opt', '-XDeriveFunctor'
        , '--ghc-opt', '-XDeriveGeneric'
        , '--ghc-opt', '-XDeriveTraversable'
        , '--ghc-opt', '-XFlexibleContexts'
        , '--ghc-opt', '-XFlexibleInstances'
        , '--ghc-opt', '-XGADTSyntax'
        , '--ghc-opt', '-XMultiParamTypeClasses'
        , '--ghc-opt', '-XNumericUnderscores'
        , '--ghc-opt', '-XRankNTypes'
        , '--ghc-opt', '-XScopedTypeVariables'
        , '--ghc-opt', '-XStandaloneDeriving'
        , '--ghc-opt', '-XTupleSections'
        , '--ghc-opt', '-XTypeApplications'
        , '--ghc-opt', '-XTypeOperators'
        , '--ghc-opt', '-XImportQualifiedPost'
        , '--ghc-opt', '-XLambdaCase'
        ]
