restylers_version: dev
restylers:
  - fourmolu:
      arguments:
        - '-o -XBangPatterns'
        - '-o -XDeriveAnyClass'
        - '-o -XDeriveDataTypeable'
        - '-o -XDeriveFunctor'
        - '-o -XDeriveGeneric'
        - '-o -XDeriveTraversable'
        - '-o -XFlexibleContexts'
        - '-o -XFlexibleInstances'
        - '-o -XGADTSyntax'
        - '-o -XMultiParamTypeClasses'
        - '-o -XNumericUnderscores'
        - '-o -XRankNTypes'
        - '-o -XScopedTypeVariables'
        - '-o -XStandaloneDeriving'
        - '-o -XTupleSections'
        - '-o -XTypeApplications'
        - '-o -XTypeOperators'
        - '-o -XImportQualifiedPost'
        - '-o -XLambdaCase'
