blank_issues_enabled: true
contact_links:
  - name: Swarm Community
    url: https://github.com/swarm-game/swarm/blob/main/COMMUNITY.md
    about: Just want to give feedback or discuss Swarm?  Check out
      other ways to connect with the Swarm community.
