name: YAML normalization
on:
  push:
    paths:
      - 'data/**.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'data/**.yaml'
    branches:
      - main
jobs:
  ensure-yaml-normalization:
    name: Ensure YAML files are normalized
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup yq'
        uses: dcarbone/install-yq-action@v1.1.1
        with:
          version: "v4.35.1"
          download-compressed: true
      - uses: actions/checkout@v4
      - name: Normalize
        run: |
          scripts/normalize/yaml.sh
          git diff --name-only --exit-code
